var qns = [
  {
    question_id: "1",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM1",
    nucleophile: "basicN1",
    solvent: "basicS1",
    carbocation: "",
    leaving_group: "",
    product: "basicP1",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material has less static hinderance.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "2",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM2",
    nucleophile: "basicN2",
    solvent: "basicS2",
    carbocation: "",
    leaving_group: "",
    product: "basicP2",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "3",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM3",
    nucleophile: "basicN3",
    solvent: "basicS3",
    carbocation: "",
    leaving_group: "",
    product: "basicP3",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material has less static hinderance.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "4",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM4",
    nucleophile: "basicN4",
    solvent: "basicS4",
    carbocation: "",
    leaving_group: "",
    product: "basicP4",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material has less steric hinderance.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "5",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM5",
    nucleophile: "basicN5",
    solvent: "basicS5",
    carbocation: "",
    leaving_group: "",
    product: "basicP5",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "6",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM6",
    nucleophile: "basicN6",
    solvent: "basicS6",
    carbocation: "",
    leaving_group: "",
    product: "basicP6",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "7",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM7",
    nucleophile: "basicN7",
    solvent: "basicS7",
    carbocation: "",
    leaving_group: "",
    product: "basicP7",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material with high steric hinderance inhibits nucleophile attack.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "8",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM8",
    nucleophile: "basicN8",
    solvent: "basicS8",
    carbocation: "basicC8",
    leaving_group: "",
    product: "basicP8",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material with high steric hinderance inhibits nucleophile attack.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "9",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM9",
    nucleophile: "basicN9",
    solvent: "basicS9",
    carbocation: "",
    leaving_group: "",
    product: "basicP9",
    product2: "basicPP9",
    product3: "basicPPP9",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "10",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM10",
    nucleophile: "basicN10",
    solvent: "basicS10",
    carbocation: "",
    leaving_group: "",
    product: "basicP10",
    product2: "basicPP10",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material with high steric hinderance inhibits nucleophile attack.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "11",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM11",
    nucleophile: "basicN11",
    solvent: "basicS11",
    carbocation: "",
    leaving_group: "",
    product: "basicP11",
    product2: "basicPP11",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material has less steric hinderance.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "12",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM12",
    nucleophile: "basicN12",
    solvent: "basicS12",
    carbocation: "",
    leaving_group: "",
    product: "basicP12",
    product2: "basicPP12",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "13",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM13",
    nucleophile: "basicN13",
    solvent: "basicS13",
    carbocation: "",
    leaving_group: "",
    product: "basicP13",
    product2: "basicPP13",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Starting material has less steric hinderance.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "14",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM14",
    nucleophile: "basicN14",
    solvent: "basicS14",
    carbocation: "",
    leaving_group: "",
    product: "basicP14",
    product2: "basicPP14",
    product3: "basicPPP14",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "15",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM15",
    nucleophile: "basicN15",
    solvent: "basicS15",
    carbocation: "",
    leaving_group: "",
    product: "basicP15",
    product2: "basicPP15",
    product3: "basicPPP15",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "16",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM16",
    nucleophile: "basicN16",
    solvent: "basicS16",
    carbocation: "",
    leaving_group: "",
    product: "basicP16",
    product2: "basicPP16",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Undergoes either SN1 or SN2 depending on the Nucleophile and Solvent.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "17",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM17",
    nucleophile: "basicN17",
    solvent: "basicS17",
    carbocation: "",
    leaving_group: "",
    product: "basicP17",
    product2: "basicPP17",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Undergoes either SN1 or SN2 depending on the Nucleophile and Solvent.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "18",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Basic",
    starting_material: "basicSM18",
    nucleophile: "basicN18",
    solvent: "basicS18",
    carbocation: "",
    leaving_group: "",
    product: "basicP18",
    product2: "basicPP18",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "Heat favours elimination reaction.",
    extra: "",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "19",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM1",
    nucleophile: "intermediateN1",
    solvent: "intermediateS1",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "20",
    prompt: "What is the starting material, solvent and reaction type?",
    difficulty: "Intermediate",
    starting_material: "startingMaterialOption",
    nucleophile: "intermediateN2",
    solvent: "solventOption",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP2",
    product2: "intermediatePP2",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "startingMaterial,solvent,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "21",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM3",
    nucleophile: "intermediateN3",
    solvent: "intermediateS3",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "intermediatePP3",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "22",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM4",
    nucleophile: "intermediateN4",
    solvent: "intermediateS4",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "23",
    prompt: "What is the leaving group and product of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM5",
    nucleophile: "intermediateN5",
    solvent: "intermediateS5",
    carbocation: "",
    leaving_group: "leavingGroupOption",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "intermediateRT5",
    hint: "",
    extra: "",
    optionType: "leavingGroup,product",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "24",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM6",
    nucleophile: "intermediateN6",
    solvent: "intermediateS6",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "intermediatePP6",
    product3: "intermediatePPP6",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "25",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM7",
    nucleophile: "intermediateN7",
    solvent: "intermediateS7",
    carbocation: "",
    leaving_group: "leavingGroupOption",
    product: "",
    product2: "",
    product3: "",
    reaction_type: "intermediateRT7",
    hint: "",
    extra: "",
    optionType: "leavingGroup",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "26",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "startingMaterialOption",
    nucleophile: "intermediateN8",
    solvent: "intermediateS8",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP8",
    product2: "intermediatePP8",
    product3: "",
    reaction_type: "intermediateRT8",
    hint: "",
    extra: "",
    optionType: "startingMaterial",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "27",
    prompt: "What is the product of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM9",
    nucleophile: "intermediateN9",
    solvent: "intermediateS9",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "intermediateRT9",
    hint: "",
    extra: "",
    optionType: "product",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "28",
    prompt: "What is the product of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM10",
    nucleophile: "intermediateN10",
    solvent: "intermediateS10",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "intermediateRT10",
    hint: "",
    extra: "",
    optionType: "product",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "29",
    prompt: "What is the product of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM11",
    nucleophile: "intermediateN11",
    solvent: "intermediateS11",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "30",
    prompt: "What is the starting material of the equation below?",
    difficulty: "Intermediate",
    starting_material: "startingMaterialOption",
    nucleophile: "intermediateN12",
    solvent: "intermediateS12",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP12",
    product2: "intermediatePP12",
    product3: "",
    reaction_type: "intermediateRT12",
    hint: "",
    extra: "",
    optionType: "startingMaterial",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "31",
    prompt: "What is the solvent and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM13",
    nucleophile: "intermediateN13",
    solvent: "solventOption",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP13",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "solvent,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "32",
    prompt:
      "What is the starting material and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "startingMaterialOption",
    nucleophile: "intermediateN14",
    solvent: "intermediateS14",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP14",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "startingMaterial,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "33",
    prompt: "What is the starting material of the equation below?",
    difficulty: "Intermediate",
    starting_material: "startingMaterialOption",
    nucleophile: "intermediateN15",
    solvent: "intermediateS15",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP15",
    product2: "intermediatePP15",
    product3: "",
    reaction_type: "intermediateRT15",
    hint: "",
    extra: "",
    optionType: "startingMaterial",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "34",
    prompt: "What is the solvent of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM16",
    nucleophile: "intermediateN16",
    solvent: "solventOption",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP16",
    product2: "intermediatePP16",
    product3: "",
    reaction_type: "intermediateRT16",
    hint: "",
    extra: "",
    optionType: "solvent",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "35",
    prompt:
      "What is the starting material and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM17",
    nucleophile: "intermediateN17",
    solvent: "intermediateS17",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP17",
    product2: "intermediatePP17",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "startingMaterial,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "36",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM18",
    nucleophile: "intermediateN18",
    solvent: "intermediateS18",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "37",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM19",
    nucleophile: "intermediateN19",
    solvent: "intermediateS19",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "intermediatePP19",
    product3: "intermediatePPP19",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "38",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM20",
    nucleophile: "intermediateN20",
    solvent: "solventOption",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP20",
    product2: "intermediatePP20",
    product3: "intermediatePPP20",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "solvent,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "39",
    prompt: "What is the starting material of the equation below?",
    difficulty: "Intermediate",
    starting_material: "startingMaterialOption",
    nucleophile: "intermediateN21",
    solvent: "intermediateS21",
    carbocation: "",
    leaving_group: "",
    product: "intermediateP21",
    product2: "intermediatePP21",
    product3: "",
    reaction_type: "intermediateRT21",
    hint: "",
    extra: "",
    optionType: "startingMaterial",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "40",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Intermediate",
    starting_material: "intermediateSM22",
    nucleophile: "intermediateN22",
    solvent: "intermediateS22",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "intermediatePP22",
    product3: "intermediatePPP22",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "41",
    prompt: "What is the carbocation of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM1",
    nucleophile: "advancedN1",
    solvent: "advancedS1",
    carbocation: "carbocationOption",
    leaving_group: "",
    product: "advancedP1",
    product2: "advancedPP1",
    product3: "",
    reaction_type: "",
    hint: "",
    extra: "advancedE1",
    optionType: "carbocation",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "42",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM2",
    nucleophile: "",
    solvent: "",
    carbocation: "",
    leaving_group: "",
    product: "advancedP2",
    product2: "advancedPP2",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "advancedE2",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "43",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "",
    nucleophile: "advancedN3",
    solvent: "advancedS3",
    carbocation: "",
    leaving_group: "",
    product: "advancedP3",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "advancedE3",
    optionType: "reactionType",
    arrow: "arrowTri",
    didYouKnow: "advancedDYK3",
  },
  {
    question_id: "44",
    prompt: "What is the starting material of the equation below?",
    difficulty: "Advanced",
    starting_material: "startingMaterialOption",
    nucleophile: "advancedN4",
    solvent: "advancedS4",
    carbocation: "",
    leaving_group: "",
    product: "advancedP4",
    product2: "",
    product3: "",
    reaction_type: "advancedRT4",
    hint: "",
    extra: "",
    optionType: "startingMaterial",
    arrow: "arrow",
    didYouKnow: "advancedDYK4",
  },
  {
    question_id: "45",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM5",
    nucleophile: "advancedN5",
    solvent: "advancedS5",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrow",
    didYouKnow: "advancedDYK5",
  },
  {
    question_id: "46",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM6",
    nucleophile: "advancedN6",
    solvent: "advancedS6",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "advancedPP6",
    product3: "advancedPPP6",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "47",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM7",
    nucleophile: "advancedN7",
    solvent: "",
    carbocation: "",
    leaving_group: "",
    product: "advancedP7",
    product2: "advancedPP7",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "48",
    prompt: "What is the reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM8",
    nucleophile: "advancedN8",
    solvent: "",
    carbocation: "",
    leaving_group: "",
    product: "advancedP8",
    product2: "advancedPP8",
    product3: "",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "49",
    prompt: "What is the carbocation of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM9",
    nucleophile: "advancedN9",
    solvent: "advancedS9",
    carbocation: "carbocationOption",
    leaving_group: "",
    product: "advancedP9",
    product2: "advancedPP9",
    product3: "",
    reaction_type: "",
    hint: "",
    extra: "advancedE9",
    optionType: "carbocation",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "50",
    prompt: "What is the starting material of the equation below?",
    difficulty: "Advanced",
    starting_material: "startingMaterialOption",
    nucleophile: "advancedN10",
    solvent: "advancedS10",
    carbocation: "",
    leaving_group: "",
    product: "advancedP10",
    product2: "",
    product3: "",
    reaction_type: "advancedRT10",
    hint: "",
    extra: "advancedE10",
    optionType: "startingMaterial",
    arrow: "arrow",
    didYouKnow: "advancedDYK10",
  },
  {
    question_id: "51",
    prompt: "What is the starting material of the equation below?",
    difficulty: "Advanced",
    starting_material: "startingMaterialOption",
    nucleophile: "advancedN11",
    solvent: "advancedS11",
    carbocation: "",
    leaving_group: "",
    product: "advancedP11",
    product2: "advancedPP11",
    product3: "",
    reaction_type: "advancedRT11",
    hint: "",
    extra: "",
    optionType: "startingMaterial",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "52",
    prompt: "What is the product of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM12",
    nucleophile: "advancedN12",
    solvent: "advancedS12",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "advancedRT12",
    hint: "",
    extra: "",
    optionType: "product",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "53",
    prompt: "What is the product of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM13",
    nucleophile: "advancedN13",
    solvent: "advancedS13",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "",
    product3: "",
    reaction_type: "advancedRT13",
    hint: "",
    extra: "",
    optionType: "product",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "54",
    prompt: "What is the solvent of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM14",
    nucleophile: "advancedN14",
    solvent: "solventOption",
    carbocation: "",
    leaving_group: "",
    product: "advancedP14",
    product2: "",
    product3: "",
    reaction_type: "advancedRT14",
    hint: "",
    extra: "",
    optionType: "solvent",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "55",
    prompt: "What is the carbocation and product of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM15",
    nucleophile: "advancedN15",
    solvent: "advancedS15",
    carbocation: "carbocationOption",
    leaving_group: "",
    product: "advancedP15",
    product2: "advancedPP15",
    product3: "productOption",
    reaction_type: "advancedRT15",
    hint: "",
    extra: "",
    optionType: "carbocation,product",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "56",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM16",
    nucleophile: "advancedN16",
    solvent: "advancedS16",
    carbocation: "",
    leaving_group: "",
    product: "advancedP16",
    product2: "productOption",
    product3: "advancedPPP16",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "57",
    prompt: "What is the product and reaction type of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM17",
    nucleophile: "advancedN17",
    solvent: "advancedS17",
    carbocation: "",
    leaving_group: "",
    product: "advancedP17",
    product2: "advancedPP17",
    product3: "productOption",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "product,reactionType",
    arrow: "arrow",
    didYouKnow: "",
  },
  {
    question_id: "58",
    prompt: "What is the solvent and product of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM18",
    nucleophile: "advancedN18",
    solvent: "solventOption",
    carbocation: "",
    leaving_group: "",
    product: "productOption",
    product2: "advancedPP18",
    product3: "advancedPPP18",
    reaction_type: "advancedRT18",
    hint: "",
    extra: "",
    optionType: "solvent,product",
    arrow: "arrowTri",
    didYouKnow: "",
  },
  {
    question_id: "59",
    prompt: "What is the reaction type and product of the equation below?",
    difficulty: "Advanced",
    starting_material: "advancedSM19",
    nucleophile: "advancedN19",
    solvent: "advancedS19",
    carbocation: "",
    leaving_group: "",
    product: "advancedP19",
    product2: "productOption",
    product3: "advancedPPP19",
    reaction_type: "reactionTypeOption",
    hint: "",
    extra: "",
    optionType: "reactionType,product",
    arrow: "arrowTri",
    didYouKnow: "",
  },
];

exports.questions = qns;
