var qnsChoices = [
  {
    choice_id: "1",
    choice: "basicQ1RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "1",
  },
  {
    choice_id: "2",
    choice: "basicQ1RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "1",
  },
  {
    choice_id: "3",
    choice: "basicQ1RT3",
    is_correct_choice: "True",
    name: "E1",
    question_id: "1",
  },
  {
    choice_id: "4",
    choice: "basicQ1RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "1",
  },
  {
    choice_id: "5",
    choice: "basicQ2RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "2",
  },
  {
    choice_id: "6",
    choice: "basicQ2RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "2",
  },
  {
    choice_id: "7",
    choice: "basicQ2RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "2",
  },
  {
    choice_id: "8",
    choice: "basicQ2RT4",
    is_correct_choice: "True",
    name: "E2",
    question_id: "2",
  },
  {
    choice_id: "9",
    choice: "basicQ3RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "3",
  },
  {
    choice_id: "10",
    choice: "basicQ3RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "3",
  },
  {
    choice_id: "11",
    choice: "basicQ3RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "3",
  },
  {
    choice_id: "12",
    choice: "basicQ3RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "3",
  },
  {
    choice_id: "13",
    choice: "basicQ4RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "4",
  },
  {
    choice_id: "14",
    choice: "basicQ4RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "4",
  },
  {
    choice_id: "15",
    choice: "basicQ4RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "4",
  },
  {
    choice_id: "16",
    choice: "basicQ4RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "4",
  },
  {
    choice_id: "17",
    choice: "basicQ5RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "5",
  },
  {
    choice_id: "18",
    choice: "basicQ5RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "5",
  },
  {
    choice_id: "19",
    choice: "basicQ5RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "5",
  },
  {
    choice_id: "20",
    choice: "basicQ5RT4",
    is_correct_choice: "True",
    name: "E2",
    question_id: "5",
  },
  {
    choice_id: "21",
    choice: "basicQ6RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "6",
  },
  {
    choice_id: "22",
    choice: "basicQ6RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "6",
  },
  {
    choice_id: "23",
    choice: "basicQ6RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "6",
  },
  {
    choice_id: "24",
    choice: "basicQ6RT4",
    is_correct_choice: "True",
    name: "E2",
    question_id: "6",
  },
  {
    choice_id: "25",
    choice: "basicQ7RT1",
    is_correct_choice: "True",
    name: "SN1",
    question_id: "7",
  },
  {
    choice_id: "26",
    choice: "basicQ7RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "7",
  },
  {
    choice_id: "27",
    choice: "basicQ7RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "7",
  },
  {
    choice_id: "28",
    choice: "basicQ7RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "7",
  },
  {
    choice_id: "29",
    choice: "basicQ8RT1",
    is_correct_choice: "True",
    name: "SN1",
    question_id: "8",
  },
  {
    choice_id: "30",
    choice: "basicQ8RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "8",
  },
  {
    choice_id: "31",
    choice: "basicQ8RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "8",
  },
  {
    choice_id: "32",
    choice: "basicQ8RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "8",
  },
  {
    choice_id: "33",
    choice: "basicQ9RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "9",
  },
  {
    choice_id: "34",
    choice: "basicQ9RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "9",
  },
  {
    choice_id: "35",
    choice: "basicQ9RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "9",
  },
  {
    choice_id: "36",
    choice: "basicQ9RT4",
    is_correct_choice: "True",
    name: "E2",
    question_id: "9",
  },
  {
    choice_id: "37",
    choice: "basicQ10RT1",
    is_correct_choice: "True",
    name: "SN1",
    question_id: "10",
  },
  {
    choice_id: "38",
    choice: "basicQ10RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "10",
  },
  {
    choice_id: "39",
    choice: "basicQ10RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "10",
  },
  {
    choice_id: "40",
    choice: "basicQ10RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "10",
  },
  {
    choice_id: "41",
    choice: "basicQ11RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "11",
  },
  {
    choice_id: "42",
    choice: "basicQ11RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "11",
  },
  {
    choice_id: "43",
    choice: "basicQ11RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "11",
  },
  {
    choice_id: "44",
    choice: "basicQ11RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "11",
  },
  {
    choice_id: "45",
    choice: "basicQ12RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "12",
  },
  {
    choice_id: "46",
    choice: "basicQ12RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "12",
  },
  {
    choice_id: "47",
    choice: "basicQ12RT3",
    is_correct_choice: "True",
    name: "E1",
    question_id: "12",
  },
  {
    choice_id: "48",
    choice: "basicQ12RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "12",
  },
  {
    choice_id: "49",
    choice: "basicQ13RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "13",
  },
  {
    choice_id: "50",
    choice: "basicQ13RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "13",
  },
  {
    choice_id: "51",
    choice: "basicQ13RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "13",
  },
  {
    choice_id: "52",
    choice: "basicQ13RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "13",
  },
  {
    choice_id: "53",
    choice: "basicQ14RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "14",
  },
  {
    choice_id: "54",
    choice: "basicQ14RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "14",
  },
  {
    choice_id: "55",
    choice: "basicQ14RT3",
    is_correct_choice: "True",
    name: "E1",
    question_id: "14",
  },
  {
    choice_id: "56",
    choice: "basicQ14RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "14",
  },
  {
    choice_id: "57",
    choice: "basicQ15RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "15",
  },
  {
    choice_id: "58",
    choice: "basicQ15RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "15",
  },
  {
    choice_id: "59",
    choice: "basicQ15RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "15",
  },
  {
    choice_id: "60",
    choice: "basicQ15RT4",
    is_correct_choice: "True",
    name: "E2",
    question_id: "15",
  },
  {
    choice_id: "61",
    choice: "basicQ16RT1",
    is_correct_choice: "True",
    name: "SN1",
    question_id: "16",
  },
  {
    choice_id: "62",
    choice: "basicQ16RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "16",
  },
  {
    choice_id: "63",
    choice: "basicQ16RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "16",
  },
  {
    choice_id: "64",
    choice: "basicQ16RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "16",
  },
  {
    choice_id: "65",
    choice: "basicQ17RT1",
    is_correct_choice: "True",
    name: "SN1",
    question_id: "17",
  },
  {
    choice_id: "66",
    choice: "basicQ17RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "17",
  },
  {
    choice_id: "67",
    choice: "basicQ17RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "17",
  },
  {
    choice_id: "68",
    choice: "basicQ17RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "17",
  },
  {
    choice_id: "69",
    choice: "basicQ18RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "18",
  },
  {
    choice_id: "70",
    choice: "basicQ18RT2",
    is_correct_choice: "False",
    name: "SN2",
    question_id: "18",
  },
  {
    choice_id: "71",
    choice: "basicQ18RT3",
    is_correct_choice: "True",
    name: "E1",
    question_id: "18",
  },
  {
    choice_id: "72",
    choice: "basicQ18RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "18",
  },
  {
    choice_id: "73",
    choice: "intermediateQ1RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "19",
  },
  {
    choice_id: "74",
    choice: "intermediateQ1RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "19",
  },
  {
    choice_id: "75",
    choice: "intermediateQ1RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "19",
  },
  {
    choice_id: "76",
    choice: "intermediateQ1RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "19",
  },
  {
    choice_id: "77",
    choice: "intermediateQ1P1",
    is_correct_choice: "False",
    name: "Product 1",
    question_id: "19",
  },
  {
    choice_id: "78",
    choice: "intermediateQ1P2",
    is_correct_choice: "False",
    name: "Product 2",
    question_id: "19",
  },
  {
    choice_id: "79",
    choice: "intermediateQ1P3",
    is_correct_choice: "True",
    name: "Product 3",
    question_id: "19",
  },
  {
    choice_id: "80",
    choice: "intermediateQ1P4",
    is_correct_choice: "False",
    name: "Product 4",
    question_id: "19",
  },
  {
    choice_id: "81",
    choice: "intermediateQ2SM1",
    is_correct_choice: "False",
    name: "Starting Material 1",
    question_id: "20",
  },
  {
    choice_id: "82",
    choice: "intermediateQ2SM2",
    is_correct_choice: "False",
    name: "Starting Material 2",
    question_id: "20",
  },
  {
    choice_id: "83",
    choice: "intermediateQ2SM3",
    is_correct_choice: "False",
    name: "Starting Material 3",
    question_id: "20",
  },
  {
    choice_id: "84",
    choice: "intermediateQ2SM4",
    is_correct_choice: "True",
    name: "Starting Material 4",
    question_id: "20",
  },
  {
    choice_id: "85",
    choice: "intermediateQ2S1",
    is_correct_choice: "False",
    name: "Protic",
    question_id: "20",
  },
  {
    choice_id: "86",
    choice: "intermediateQ2S2",
    is_correct_choice: "True",
    name: "Aprotic",
    question_id: "20",
  },
  {
    choice_id: "87",
    choice: "intermediateQ2RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "20",
  },
  {
    choice_id: "88",
    choice: "intermediateQ2RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "20",
  },
  {
    choice_id: "89",
    choice: "intermediateQ2RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "20",
  },
  {
    choice_id: "90",
    choice: "intermediateQ2RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "20",
  },
  {
    choice_id: "91",
    choice: "intermediateQ3P1",
    is_correct_choice: "False",
    name: "Product 1",
    question_id: "21",
  },
  {
    choice_id: "92",
    choice: "intermediateQ3P2",
    is_correct_choice: "False",
    name: "Product 2",
    question_id: "21",
  },
  {
    choice_id: "93",
    choice: "intermediateQ3P3",
    is_correct_choice: "False",
    name: "Product 3",
    question_id: "21",
  },
  {
    choice_id: "94",
    choice: "intermediateQ3P4",
    is_correct_choice: "True",
    name: "Product 4",
    question_id: "21",
  },
  {
    choice_id: "95",
    choice: "intermediateQ3RT1",
    is_correct_choice: "False",
    name: "SN1",
    question_id: "21",
  },
  {
    choice_id: "96",
    choice: "intermediateQ3RT2",
    is_correct_choice: "True",
    name: "SN2",
    question_id: "21",
  },
  {
    choice_id: "97",
    choice: "intermediateQ3RT3",
    is_correct_choice: "False",
    name: "E1",
    question_id: "21",
  },
  {
    choice_id: "98",
    choice: "intermediateQ3RT4",
    is_correct_choice: "False",
    name: "E2",
    question_id: "21",
  },
];
